services:
  mongo:
    image: mongo:7.0
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: librarydb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      
      
    networks:
      - libmgmt_network_mongo
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 20s
      retries: 10

  backend:
    build: ./backend
    container_name: libmgmt_backend_mongo
    restart: always
    env_file:
    - ./backend/.env
    ports:
      - "5000:5000"
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - libmgmt_network_mongo
    

  frontend:
    build: ./frontend
    container_name: libmgmt_frontend_mongo
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - libmgmt_network_mongo
    environment:
      - VITE_API_URL=http://localhost:5000
  seeder:
    build: ./backend
    container_name: libmgmt_seeder
    command: node seeder.js
    depends_on:
      - mongo
    networks:
      - libmgmt_network_mongo


volumes:
  mongo_data:

networks:
  libmgmt_network_mongo:
    driver: bridge